"""Generates data assertions from the migrations themselves.

The question "is the data exactly what we put in" has a precise answer only
because the migrations ARE the specification. Rather than hand-writing checks
and hoping they stay in step, this reads them and emits SQL that asserts what
they claim.

Checks produced:
  - every ingredient the icon migrations name exists, with the right
    icon_key and category
  - every name merged away is genuinely gone
  - every alias from migration 016 is present on the right row
  - nothing has quietly drifted (extra icon_keys, wrong categories)

    python tools/gen_data_assertions.py
    # paste out/verify_data.sql into the Supabase SQL Editor
"""

import pathlib
import re

MIG = pathlib.Path("supabase/migrations")
OUT = pathlib.Path("out")

# ('salt','spice','salt')  ->  name, category, icon_key
ICON_TUPLE = re.compile(
    r"\(\s*'([a-z0-9 ]+)'\s*,\s*'([a-z_0-9]+)'\s*,\s*'([a-z_0-9]+)'\s*\)")
MERGE = re.compile(r"merge_ingredient\(\s*'([^']+)'\s*,\s*'([^']+)'\s*\)")
ALIAS = re.compile(r"\(\s*'([a-z0-9 ]+)'\s*,\s*array\[([^\]]*)\]\s*\)")

# Only these files carry icon/category tuples in that shape; the others match
# the pattern by coincidence and would produce nonsense assertions.
ICON_FILES = ("ingredient_icons", "round2")


def sq(v):
    return "'" + v.replace("'", "''") + "'"


def main():
    OUT.mkdir(exist_ok=True)
    icons, merges, aliases = {}, {}, {}

    for f in sorted(MIG.glob("*.sql")):
        text = f.read_text(encoding="utf-8")

        if any(k in f.name for k in ICON_FILES):
            for name, category, icon in ICON_TUPLE.findall(text):
                icons[name] = (category, icon)

        for src, dst in MERGE.findall(text):
            if src != dst:
                merges[src] = dst

        if "ingredient_aliases" in f.name:
            for canonical, raw in ALIAS.findall(text):
                found = re.findall(r"'([^']+)'", raw)
                if found:
                    aliases[canonical] = sorted(set(found))

    # A merge is only still expected if a LATER migration did not reverse it.
    #
    # Migration 005 merged besan -> gram flour; migrations 010/012 then declared
    # besan canonical with its own icon. The second decision wins. Asserting the
    # first produced 11 false "MERGE UNDONE" failures against perfectly correct
    # data, which is worse than no check — it trains you to ignore the output.
    superseded = {src for src in merges if src in icons}
    for src in superseded:
        merges.pop(src, None)
    if superseded:
        print(f"  merges superseded by later migrations: {len(superseded)}")
        print(f"    {', '.join(sorted(superseded))}")

    # Aliases declared for a name that no migration ever made canonical were
    # never applied. Report them once here rather than as one failure per alias.
    orphan_alias_targets = {n for n in aliases if n not in icons}
    if orphan_alias_targets:
        print(f"  alias groups whose target is not a canonical name: "
              f"{len(orphan_alias_targets)}")
        for n in sorted(orphan_alias_targets):
            aliases.pop(n, None)

    print(f"  icon/category assertions : {len(icons)}")
    print(f"  merged-away names        : {len(merges)}")
    print(f"  alias rows               : {len(aliases)} "
          f"({sum(len(v) for v in aliases.values())} aliases)")

    lines = [
        "-- GENERATED by tools/gen_data_assertions.py — do not hand-edit.",
        "-- Asserts the database matches what the migrations declare.",
        "-- Read-only. Anything returned is a discrepancy; an empty result is a pass.",
        "",
        "with",
        "expected_icons(name, category, icon_key) as (values",
        ",\n".join(f"  ({sq(n)}, {sq(c)}, {sq(i)})" for n, (c, i) in sorted(icons.items())),
        "),",
        "merged_away(name, merged_into) as (values",
        ",\n".join(f"  ({sq(a)}, {sq(b)})" for a, b in sorted(merges.items())),
        "),",
        "expected_aliases(name, alias) as (values",
        ",\n".join(f"  ({sq(n)}, {sq(a)})"
                   for n, al in sorted(aliases.items()) for a in al),
        ")",
        "",
        "select * from (",
        "",
        "  -- an ingredient the migrations create is missing entirely",
        "  select 'MISSING INGREDIENT' as issue, e.name as subject,",
        "         'declared in a migration, not in the table' as detail",
        "  from expected_icons e",
        "  where not exists (select 1 from public.ingredients i",
        "                    where lower(i.name) = e.name)",
        "",
        "  union all",
        "  -- present, but the icon_key drifted from what was declared",
        "  select 'WRONG ICON_KEY', i.name,",
        "         'expected ' || e.icon_key || ', found ' ||",
        "         coalesce(i.icon_key, 'NULL')",
        "  from expected_icons e",
        "  join public.ingredients i on lower(i.name) = e.name",
        "  where i.icon_key is distinct from e.icon_key",
        "",
        "  union all",
        "  select 'WRONG CATEGORY', i.name,",
        "         'expected ' || e.category || ', found ' ||",
        "         coalesce(i.category, 'NULL')",
        "  from expected_icons e",
        "  join public.ingredients i on lower(i.name) = e.name",
        "  where i.category is distinct from e.category",
        "",
        "  union all",
        "  -- a merged name came back, so a later import recreated a duplicate",
        "  select 'MERGE UNDONE', m.name,",
        "         'was merged into ' || m.merged_into || ' but exists again'",
        "  from merged_away m",
        "  where exists (select 1 from public.ingredients i",
        "                where lower(i.name) = m.name)",
        "",
        "  union all",
        "  -- the row the merge pointed at should still be there",
        "  select 'MERGE TARGET MISSING', m.merged_into,",
        "         m.name || ' was merged into it, but it does not exist'",
        "  from merged_away m",
        "  where not exists (select 1 from public.ingredients i",
        "                    where lower(i.name) = m.merged_into)",
        "",
        "  union all",
        "  -- an alias declared in migration 016 never landed",
        "  select 'MISSING ALIAS', e.name, 'alias ' || e.alias || ' not present'",
        "  from expected_aliases e",
        "  join public.ingredients i on lower(i.name) = e.name",
        "  where not (e.alias = any(i.aliases))",
        "",
        "  union all",
        "  -- the row the alias belongs on is gone",
        "  select 'ALIAS ROW MISSING', e.name,",
        "         'aliases declared for an ingredient that does not exist'",
        "  from (select distinct name from expected_aliases) e",
        "  where not exists (select 1 from public.ingredients i",
        "                    where lower(i.name) = e.name)",
        "",
        ") discrepancies",
        "order by issue, subject;",
    ]
    (OUT / "verify_data.sql").write_text("\n".join(lines), encoding="utf-8")
    print(f"\n  -> out/verify_data.sql")
    print("  Paste into the SQL Editor. An empty result means the data matches")
    print("  the migrations exactly. Any row is a discrepancy.")


if __name__ == "__main__":
    main()
