"""Generates one complete database audit.

    python tools/gen_full_audit.py
    # paste out/audit.sql into the Supabase SQL Editor

Read-only. Returns a single table: section, severity, check, result, detail.
Empty of FAIL rows means the database is sound.

Why generated rather than a static file: half these checks assert what the
migrations declare — icon mappings, merges, aliases. Written by hand they drift
from the migrations within a week and start reporting failures against correct
data, which is how a check becomes noise you learn to ignore.
"""

import pathlib
import re

MIG = pathlib.Path("supabase/migrations")
OUT = pathlib.Path("out")

ICON_TUPLE = re.compile(r"\(\s*'([a-z0-9 ]+)'\s*,\s*'([a-z_0-9]+)'\s*,\s*'([a-z_0-9]+)'\s*\)")
MERGE = re.compile(r"merge_ingredient\(\s*'([^']+)'\s*,\s*'([^']+)'\s*\)")
ALIAS = re.compile(r"\(\s*'([a-z0-9 ]+)'\s*,\s*array\[([^\]]*)\]\s*\)")
ICON_FILES = ("ingredient_icons", "round2")

TABLES = ["profiles", "categories", "recipes", "ingredients", "recipe_ingredients",
          "favorites", "collections", "reviews", "reports", "user_allergies",
          "user_pantry_staples", "shopping_list_items", "meal_plan_entries",
          "cooked_history"]

FUNCTIONS = ["match_recipes_for_user", "profile_stats", "distinct_diets",
             "distinct_cuisines", "is_admin", "handle_new_user",
             "merge_ingredient", "search_ingredients"]


def sq(v):
    return "'" + str(v).replace("'", "''") + "'"


def read_migrations():
    icons, merges, aliases = {}, {}, {}
    for f in sorted(MIG.glob("*.sql")):
        t = f.read_text(encoding="utf-8")
        if any(k in f.name for k in ICON_FILES):
            for n, c, i in ICON_TUPLE.findall(t):
                icons[n] = (c, i)
        for a, b in MERGE.findall(t):
            if a != b:
                merges[a] = b
        if "ingredient_aliases" in f.name or "post_import_repair" in f.name:
            for n, raw in ALIAS.findall(t):
                found = re.findall(r"'([^']+)'", raw)
                if found:
                    aliases.setdefault(n, set()).update(found)

    # A merge a later migration reversed is not a rule any more.
    for src in [s for s in merges if s in icons]:
        merges.pop(src)
    # Aliases attached to a name no migration made canonical never applied.
    for n in [n for n in aliases if n not in icons]:
        aliases.pop(n)
    return icons, merges, {k: sorted(v) for k, v in aliases.items()}


def values(rows, cols):
    if not rows:
        return f"select {', '.join('null::text ' + c for c in cols)} where false"
    return "values\n" + ",\n".join("  (" + ", ".join(sq(v) for v in r) + ")" for r in rows)


def main():
    OUT.mkdir(exist_ok=True)
    icons, merges, aliases = read_migrations()
    print(f"  from migrations: {len(icons)} icon/category, {len(merges)} merges, "
          f"{sum(len(v) for v in aliases.values())} aliases")

    icon_rows = [(n, c, i) for n, (c, i) in sorted(icons.items())]
    merge_rows = sorted(merges.items())
    alias_rows = [(n, a) for n, al in sorted(aliases.items()) for a in al]
    table_rows = [(t,) for t in TABLES]
    fn_rows = [(f,) for f in FUNCTIONS]

    sql = f"""-- ===========================================================================
-- RECIPEDIA — FULL DATABASE AUDIT
-- Generated by tools/gen_full_audit.py. Do not hand-edit; regenerate.
--
-- Paste into the Supabase SQL Editor. Read-only: no writes, no locks held.
--
-- Sections
--   A  schema        tables, functions, RLS, policies
--   B  declared data does the data match what the migrations say
--   C  duplicates    including the case-insensitive ones the constraints miss
--   D  integrity     orphans and impossible states
--   E  content       whether recipes can actually be matched
--   F  user data     allergies, staples, lists, plans
--   G  security      RLS coverage and function exposure
--   H  summary       counts worth knowing
--
-- FAIL = the app depends on this and it is broken
-- WARN = works today, degrades a feature or will bite later
-- INFO = a number, not a problem
-- ===========================================================================

with
expected_tables(name) as ({values(table_rows, ['name'])}),
expected_functions(name) as ({values(fn_rows, ['name'])}),
expected_icons(name, category, icon_key) as ({values(icon_rows, ['name','category','icon_key'])}),
merged_away(name, merged_into) as ({values(merge_rows, ['name','merged_into'])}),
expected_aliases(name, alias) as ({values(alias_rows, ['name','alias'])}),

counts as (
  select
    (select count(*) from public.recipes) as recipes,
    (select count(*) from public.recipes where status = 'approved') as approved,
    (select count(*) from public.ingredients) as ingredients,
    (select count(*) from public.recipe_ingredients) as links,
    (select count(*) from public.profiles) as profiles,
    (select count(*) from public.categories) as cats,
    (select count(*) from public.profiles where role = 'admin') as admins
)

select section, severity, check_name, result, detail from (

-- ---------------------------------------------------------------- A. SCHEMA
select 'A schema' as section, 'FAIL' as severity, 'table missing' as check_name,
       e.name as result, 'declared in a migration, absent from the database' as detail
from expected_tables e
where not exists (select 1 from information_schema.tables t
                  where t.table_schema='public' and t.table_name=e.name)

union all
select 'A schema', 'FAIL', 'function missing', e.name,
       'the app calls this and it does not exist'
from expected_functions e
where not exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
                  where n.nspname='public' and p.proname=e.name)

union all
select 'A schema', 'FAIL', 'RLS disabled', c.relname,
       'the anon key can read every row in this table'
from pg_class c join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and c.relkind='r'
  and c.relname in (select name from expected_tables) and not c.relrowsecurity

union all
select 'A schema', 'FAIL', 'RLS on but no policy', t.name,
       'nobody can read this table, including the owner of the rows'
from expected_tables t
join pg_class c on c.relname=t.name
join pg_namespace n on n.oid=c.relnamespace and n.nspname='public'
where c.relrowsecurity
  and not exists (select 1 from pg_policies p
                  where p.schemaname='public' and p.tablename=t.name)

union all
-- A foreign key with no index means every parent delete scans the child table.
select 'A schema', 'WARN', 'foreign key without index',
       tc.table_name || '.' || kcu.column_name, 'joins and cascades scan'
from information_schema.table_constraints tc
join information_schema.key_column_usage kcu
  on kcu.constraint_name = tc.constraint_name and kcu.table_schema='public'
where tc.constraint_type='FOREIGN KEY' and tc.table_schema='public'
  and not exists (
    select 1 from pg_indexes i
    where i.schemaname='public' and i.tablename=tc.table_name
      and i.indexdef like '%(' || kcu.column_name || '%')

-- -------------------------------------------------------- B. DECLARED DATA
union all
select 'B declared', 'FAIL', 'ingredient missing', e.name,
       'a migration creates it; it is not there'
from expected_icons e
where not exists (select 1 from public.ingredients i where lower(i.name)=e.name)

union all
select 'B declared', 'WARN', 'icon_key drifted', i.name,
       'expected ' || e.icon_key || ', found ' || coalesce(i.icon_key,'NULL')
from expected_icons e join public.ingredients i on lower(i.name)=e.name
where i.icon_key is distinct from e.icon_key

union all
select 'B declared', 'WARN', 'category drifted', i.name,
       'expected ' || e.category || ', found ' || coalesce(i.category,'NULL')
from expected_icons e join public.ingredients i on lower(i.name)=e.name
where i.category is distinct from e.category

union all
select 'B declared', 'FAIL', 'merge undone', m.name,
       'merged into ' || m.merged_into || ', but exists again — an import '
       'recreated it and recipes are now split across two rows'
from merged_away m
where exists (select 1 from public.ingredients i where lower(i.name)=m.name)

union all
select 'B declared', 'WARN', 'alias missing', e.name,
       'alias ' || e.alias || ' was declared and is not present'
from expected_aliases e join public.ingredients i on lower(i.name)=e.name
where not (e.alias = any(i.aliases))

-- ------------------------------------------------------------ C. DUPLICATES
union all
select 'C duplicates', 'FAIL', 'ingredient name (case-insensitive)',
       lower(btrim(name)), count(*)::text || ' rows: ' ||
       string_agg(name, ' | ' order by name)
from public.ingredients group by lower(btrim(name)) having count(*)>1

union all
select 'C duplicates', 'FAIL', 'alias claimed by two ingredients', a,
       count(*)::text || ' rows: ' || string_agg(name, ' | ' order by name)
from (select name, unnest(aliases) a from public.ingredients) x
group by a having count(*)>1

union all
select 'C duplicates', 'FAIL', 'alias shadows a real ingredient', x.a,
       'alias on ' || x.name || ', but ' || i.name || ' is a real ingredient'
from (select name, unnest(aliases) a from public.ingredients) x
join public.ingredients i on lower(i.name)=x.a and lower(i.name)<>lower(x.name)

union all
select 'C duplicates', 'WARN', 'recipe title', lower(btrim(title)),
       count(*)::text || ' copies from: ' ||
       string_agg(coalesce(source_name,'user'), ' | ')
from public.recipes group by lower(btrim(title)) having count(*)>1

union all
select 'C duplicates', 'WARN', 'identical core ingredient set', left(fp,8),
       n::text || ': ' || titles
from (
  select fp, count(*) n, string_agg(title,' | ' order by title) titles
  from (
    select md5(string_agg(ri.ingredient_id::text,',' order by ri.ingredient_id)) fp,
           r.title
    from public.recipes r
    join public.recipe_ingredients ri on ri.recipe_id=r.id and ri.role='core'
    group by r.id, r.title having count(*)>=4
  ) f group by fp having count(*)>1
) d

union all
select 'C duplicates', 'WARN', 'category name', lower(btrim(name)),
       count(*)::text || ' rows'
from public.categories group by lower(btrim(name)) having count(*)>1

union all
select 'C duplicates', 'WARN', 'username', lower(btrim(username)),
       count(*)::text || ' accounts'
from public.profiles
where username is not null and btrim(username)<>''
group by lower(btrim(username)) having count(*)>1

-- ------------------------------------------------------------- D. INTEGRITY
union all
select 'D integrity', 'FAIL', 'recipe with no ingredients', count(*)::text,
       'can never be returned by match_recipes_for_user'
from public.recipes r
where not exists (select 1 from public.recipe_ingredients ri where ri.recipe_id=r.id)
having count(*)>0

union all
select 'D integrity', 'FAIL', 'recipe with no CORE ingredients', count(*)::text,
       'optional ingredients never block a match, so this can never match'
from public.recipes r
where not exists (select 1 from public.recipe_ingredients ri
                  where ri.recipe_id=r.id and ri.role='core')
having count(*)>0

union all
select 'D integrity', 'FAIL', 'shopping item with no ingredient or name',
       count(*)::text, 'renders as a blank row'
from public.shopping_list_items
where ingredient_id is null and (custom_name is null or btrim(custom_name)='')
having count(*)>0

union all
select 'D integrity', 'FAIL', 'review rating out of range', count(*)::text,
       'breaks the average and the star display'
from public.reviews where rating < 1 or rating > 5 having count(*)>0

union all
select 'D integrity', 'WARN', 'profile with no auth user', count(*)::text,
       'orphaned profile; the login no longer exists'
from public.profiles p
where not exists (select 1 from auth.users u where u.id=p.id) having count(*)>0

-- --------------------------------------------------------------- E. CONTENT
union all
select 'E content', 'FAIL', 'licensed recipe with no source_url', count(*)::text,
       'CC BY-SA requires attribution to be shown'
from public.recipes
where license is not null and (source_url is null or btrim(source_url)='')
having count(*)>0

union all
select 'E content', 'WARN', 'approved recipe with no diet', count(*)::text,
       'invisible to the diet filter and to hide-unsafe'
from public.recipes where status='approved' and (diet is null or btrim(diet)='')
having count(*)>0

union all
select 'E content', 'WARN', 'approved recipe with no cuisine', count(*)::text,
       'missing from Browse by cuisine'
from public.recipes where status='approved' and (cuisine is null or btrim(cuisine)='')
having count(*)>0

union all
select 'E content', 'WARN', 'approved recipe with no category', count(*)::text,
       'missing from the course filter'
from public.recipes where status='approved' and category_id is null
having count(*)>0

union all
select 'E content', 'WARN', 'recipe with fewer than 3 core ingredients',
       count(*)::text, 'will match almost nothing useful'
from (select recipe_id from public.recipe_ingredients where role='core'
      group by recipe_id having count(*)<3) t having count(*)>0

union all
select 'E content', 'WARN', 'recipe with no or trivial instructions',
       count(*)::text, 'cook mode shows a single step'
from public.recipes where instructions is null or length(btrim(instructions))<20
having count(*)>0

union all
select 'E content', 'WARN', 'external image URL', count(*)::text,
       'third-party hosts hotlink-block and hang; illustrations are safer'
from public.recipes
where image_url is not null and btrim(image_url)<>'' and image_url not like '%supabase%'
having count(*)>0

union all
select 'E content', 'WARN', 'ingredient with no icon_key', count(*)::text,
       'falls back to category art, then to a letter chip'
from public.ingredients where icon_key is null having count(*)>0

union all
select 'E content', 'WARN', 'ingredient with no category', count(*)::text,
       'no fallback art at all'
from public.ingredients where category is null having count(*)>0

union all
select 'E content', 'WARN', 'ingredient nothing references', count(*)::text,
       'clutters autocomplete and the staples picker'
from public.ingredients i
where not exists (select 1 from public.recipe_ingredients ri where ri.ingredient_id=i.id)
having count(*)>0

-- ------------------------------------------------------------- F. USER DATA
union all
select 'F user data', 'WARN', 'duplicate allergy rows', count(*)::text, ''
from (select user_id, ingredient_id from public.user_allergies
      group by 1,2 having count(*)>1) t having count(*)>0

union all
select 'F user data', 'WARN', 'duplicate pantry staples', count(*)::text, ''
from (select user_id, ingredient_id from public.user_pantry_staples
      group by 1,2 having count(*)>1) t having count(*)>0

union all
select 'F user data', 'WARN', 'same item twice on one open list', count(*)::text,
       'ticking one leaves the other'
from (select user_id, coalesce(ingredient_id::text, lower(btrim(custom_name))) it
      from public.shopping_list_items where checked=false
      group by 1,2 having count(*)>1) t having count(*)>0

union all
select 'F user data', 'INFO', 'collection with no recipes', count(*)::text,
       'harmless, but shows as an empty filter'
from public.collections c
where not exists (select 1 from public.favorites f where f.collection_id=c.id)
having count(*)>0

-- -------------------------------------------------------------- G. SECURITY
union all
select 'G security', 'FAIL', 'no admin account', '0',
       'the admin portal and moderation queue are unreachable'
from counts where admins = 0

union all
select 'G security', 'WARN', 'SECURITY DEFINER function', p.proname,
       'runs as its owner; confirm it is meant to bypass RLS'
from pg_proc p join pg_namespace n on n.oid=p.pronamespace
where n.nspname='public' and p.prosecdef

-- --------------------------------------------------------------- H. SUMMARY
union all select 'H summary','INFO','recipes', recipes::text,
       approved::text || ' approved' from counts
union all select 'H summary','INFO','ingredients', ingredients::text, '' from counts
union all select 'H summary','INFO','recipe_ingredients', links::text, '' from counts
union all select 'H summary','INFO','profiles', profiles::text,
       admins::text || ' admin' from counts
union all select 'H summary','INFO','categories', cats::text, '' from counts
union all
select 'H summary','INFO','avg core ingredients per recipe',
       coalesce(round(avg(c)::numeric,1)::text,'0'),
       'below 4 and scan matching is unreliable'
from (select count(*) c from public.recipe_ingredients where role='core'
      group by recipe_id) t
union all
select 'H summary','INFO','recipes with a cuisine',
       count(*) filter (where cuisine is not null)::text,
       'of ' || count(*)::text from public.recipes
union all
select 'H summary','INFO','ingredients with aliases',
       count(*) filter (where cardinality(aliases)>0)::text,
       'of ' || count(*)::text from public.ingredients

) audit
order by
  case severity when 'FAIL' then 1 when 'WARN' then 2 else 3 end,
  section, check_name;
"""
    (OUT / "audit.sql").write_text(sql, encoding="utf-8")
    print(f"  -> out/audit.sql  ({len(sql.splitlines())} lines)")


if __name__ == "__main__":
    main()
