-- Generated by tools/import_themealdb.py. Review before running.
-- Wrapped in a transaction: a bad row rolls the whole import back
-- rather than leaving the catalogue half-imported.
begin;

-- 1. ingredients that do not exist yet
insert into public.ingredients (name, category, is_pantry) values ('allspice', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('bacon', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('baking powder', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('bay leaves', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('beef', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('beef brisket', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('beef gravy', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('beef stock', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('black pepper', 'spice', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('brown sugar', 'sweetener', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('canola oil', 'oil', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('caster sugar', 'sweetener', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('celery', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('celery salt', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('cheese curds', 'dairy', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('chicken breast', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('chicken stock', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('chives', 'herb', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('cider vinegar', 'liquid', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('cinnamon', 'spice', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('clove', 'spice', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('cloves', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('cocoa', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('cornstarch', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('cream of tartar', 'dairy', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('creamed corn', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('custard', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('custard powder', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('dark chocolate', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('desiccated coconut', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('digestive biscuits', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('dill', 'herb', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('double cream', 'dairy', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('egg white', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('egg yolks', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('english mustard', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('flour', 'grain', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('frozen peas', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('garlic clove', 'spice', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('graham cracker crumbs', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('green beans', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('ham', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('heavy cream', 'dairy', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('icing sugar', 'sweetener', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('jam', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('leaves of summer savoury', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('maple syrup', 'sweetener', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('melted butter', 'dairy', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('molasses', 'sweetener', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('muscovado sugar', 'sweetener', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('mustard', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('new potatoes', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('paprika', 'spice', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('parsley', 'herb', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('pepper', 'spice', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('pitted dates', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('plain flour', 'grain', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('pork', 'meat', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('red pepper flakes', 'spice', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('russet potato', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('saskatoon berries', 'fruit', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('shortcrust pastry', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('single cream', 'dairy', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('turnips', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('unsalted butter', 'dairy', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('vanilla extract', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('vegetable shortening', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('vegetable stock', 'liquid', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('white navy beans', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('yeast', 'other', false) on conflict (name) do nothing;
insert into public.ingredients (name, category, is_pantry) values ('yellow split peas', 'other', false) on conflict (name) do nothing;

-- 2. recipes, skipping any title already present

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'BeaverTails', 'In the bowl of a stand mixer, add warm water, a big pinch of sugar and yeast. Allow to sit until frothy.
Into the same bowl, add 1/2 cup sugar, warm milk, melted butter, eggs and salt, and whisk until combined.
Place a dough hook on the mixer, add the flour with the machine on, until a smooth but slightly sticky dough forms.
Place dough in a bowl, cover with plastic wrap, and allow to proof for 1 1/2 hours.
Cut dough into 12 pieces, and roll out into long oval-like shapes about 1/4 inch thick that resemble a beaver’s tail.
In a large, deep pot, heat oil to 350 degrees. Gently place beavertail dough into hot oil and cook for 30 to 45 seconds on each side until golden brown.
Drain on paper towels, and garnish as desired. Toss in cinnamon sugar, in white sugar with a squeeze of lemon, or with a generous slathering of Nutella and a handful of toasted almonds. Enjoy!', 'https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('BeaverTails'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('water', '1/2 cup'),
  ('yeast', '2 parts'),
  ('sugar', '1/2 cup'),
  ('milk', '1/2 cup'),
  ('butter', '6 tblsp'),
  ('eggs', '2'),
  ('salt', '1 ½ tsp'),
  ('flour', '2-1/2 cups'),
  ('oil', 'for frying'),
  ('lemon', 'garnish'),
  ('sugar', 'garnish'),
  ('cinnamon', 'garnish')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Breakfast Potatoes', 'Before you do anything, freeze your bacon slices that way when you''re ready to prep, it''ll be so much easier to chop!
Wash the potatoes and cut medium dice into square pieces. To prevent any browning, place the already cut potatoes in a bowl filled with water.
In the meantime, heat 1-2 tablespoons of oil in a large skillet over medium-high heat. Tilt the skillet so the oil spreads evenly.
Once the oil is hot, drain the potatoes and add to the skillet. Season with salt, pepper, and Old Bay as needed.
Cook for 10 minutes, stirring the potatoes often, until brown. If needed, add a tablespoon more of oil.
Chop up the bacon and add to the potatoes. The bacon will start to render and the fat will begin to further cook the potatoes. Toss it up a bit! The bacon will take 5-6 minutes to crisp.
Once the bacon is cooked, reduce the heat to medium-low, add the minced garlic and toss. Season once more. Add dried or fresh parsley. Control heat as needed.
Let the garlic cook until fragrant, about one minute.
Just before serving, drizzle over the maple syrup and toss. Let that cook another minute, giving the potatoes a caramelized effect.
Serve in a warm bowl with a sunny side up egg!', 'https://www.themealdb.com/images/media/meals/1550441882.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Breakfast Potatoes'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('potatoes', '3 Medium'),
  ('olive oil', '1 tbs'),
  ('bacon', '2 strips'),
  ('garlic clove', 'Minced'),
  ('maple syrup', '1 tbs'),
  ('parsley', 'Garnish'),
  ('salt', 'Pinch'),
  ('pepper', 'Pinch'),
  ('allspice', 'To taste')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Canadian Butter Tarts', 'Preheat the oven to fan 170C/ conventional 190C/gas 5. Roll out the pastry on a lightly floured surface so it’s slightly thinner than straight from the pack. Then cut out 18-20 rounds with a 7.5cm fluted cutter, re-rolling the trimmings. Use the rounds to line two deep 12-hole tart tins (not muffin tins). If you only have a regular-sized, 12-hole tart tin you will be able to make a few more slightly shallower tarts.
Beat the eggs in a large bowl and combine with the rest of the ingredients except the walnuts. Tip this mixture into a pan and stir continuously for 3-4 minutes until the butter melts, and the mixture bubbles and starts to thicken. It should be thick enough to coat the back of a wooden spoon. Don’t overcook, and be sure to stir all the time as the mixture can easily burn. Remove from the heat and stir in the nuts.
Spoon the filling into the unbaked tart shells so it’s level with the pastry. Bake for 15-18 minutes until set and pale golden. Leave in the tin to cool for a few minutes before lifting out on to a wire rack. Serve warm or cold.', 'https://www.themealdb.com/images/media/meals/wpputp1511812960.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Canadian Butter Tarts'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('shortcrust pastry', '375g'),
  ('eggs', '2 large'),
  ('muscovado sugar', '175g'),
  ('raisins', '100g'),
  ('vanilla extract', '1 tsp'),
  ('butter', '50g'),
  ('single cream', '4 tsp'),
  ('walnuts', '50g')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Classic Tourtière', 'Heat oil on medium-high heat in a large sauté pan or skillet, then sauté the onion and garlic until softened, about 5 minutes. Add the ground beef, pork, and spices and cook until the meat is browned.
Add the beef broth and bring it up to a simmer then reduce heat to medium low. Add the grated potato and stir it in. Cook until liquid is almost absorbed, about 15 min. Remove the bay leaves and add salt to taste. Remove the pan from the heat and let the mixture cool completely — it bakes best if the filling is chilled.
Preheat the oven to 375 °F (190 °C). On a lightly floured surface, roll out one disc of the pie dough to less than the 1/4-inch thickness and line the 9-inch pie plate. Fill this with the cooled tourtière mixture and spread out evenly. Roll out the remaining dough to the same thickness, cut a hole in the centre (for steam to escape) and place on top of the filling. Trim the dough to 1/2-inch beyond the edge of the pie plate and pinch the edges of the crust together. Brush the crust with the egg wash.
Bake tourtière for about 45 minutes or until the pastry is a rich golden brown. Let cool for 15 minutes before slicing to serve.
Serves: 8-10 (makes 2 9-inch pies)', 'https://www.themealdb.com/images/media/meals/0sd7ac1764787957.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Classic Tourtière'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('canola oil', '2 tablespoons'),
  ('onion', '1 chopped'),
  ('garlic', '2 cloves minced'),
  ('beef', '1 lb'),
  ('pork', '1 lb'),
  ('leaves of summer savoury', '1 tsp'),
  ('salt', 'To taste'),
  ('pepper', 'To taste'),
  ('clove', '1/2 tsp'),
  ('nutmeg', '1/2 tsp'),
  ('bay leaf', '1'),
  ('beef stock', '1 cup'),
  ('russet potato', '1 small'),
  ('shortcrust pastry', '4'),
  ('egg', '1 beaten')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Date squares', 'Preheat oven to 350°F (180°C). Grease an 8-inch (20 cm) square baking pan.
To make the date filing: Combine the dates and water in a medium saucepan over high heat and bring to a boil. Reduce heat to low and simmer gently, stirring occasionally until the mixture thickens, around 6 to 8 minutes. Remove from heat, stir in vanilla and let cool. Set aside.
Combine rolled oats, flour, sugar, baking soda and salt in a food processor. Pulse 3 times (careful not to overmix, you don’t want the mixture to be powdery, just combined). Add butter and pulse again until the mixture is crumbly in pea-sized clumps. Transfer to a mixing bowl to thoroughly mix in the butter.
Spread half of the oat mixture on the bottom of the prepared baking pan, pressing down to make a flat, equal bottom later. Add the date mixture over the crust and then spread evenly. Layer with the remaining oat mixture and press down to flatten the top layer.
Bake in the centre of the oven until the top is golden brown, 30 to 35 minutes. Let cool completely in the pan before cutting and serving. Date Squares keep well, covered in the refrigerator for up to a week, and frozen for 2 to 3 months.', 'https://www.themealdb.com/images/media/meals/u4scbo1764446514.jpg',
         'Canadian', 'Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Date squares'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('pitted dates', '2 1/2 cups'),
  ('water', '1 cup'),
  ('vanilla', '1 1/2 cup'),
  ('oats', '2 cups'),
  ('all purpose flour', '1 cup'),
  ('brown sugar', '1 cup'),
  ('baking powder', '1/2 tsp'),
  ('salt', '1/4 tsp'),
  ('unsalted butter', '1 cup')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Figgy Duff', 'In a medium bowl, whisk together flour, brown sugar, baking powder, and spices.
Add raisins and stir well, making sure to coat the raisins in the flour mixture.
Add melted butter, molasses and water and mix with a wooden spoon. Form a ball with the spoon or your hands and put the dough ball in a cotton pudding bag. Tie the bag, leaving at least 1 inch of room to allow the pudding to expand while cooking.
Boil pudding for 1.5 hours. (In NL, this is typically done in the pot along with Jiggs Dinner, but it can be done independently.)
When the duff is firm, remove it from the boiling water and let it cool slightly before removing it from the pudding bag.
Slice pudding like a cake and serve with the warm sauce of your choice: rum butter sauce, warmed molasses or Molasses Coady sauce (1 cup (250 mL) molasses, 1/4 cup (60 mL) butter, 1/4 cup (60 mL) water) is common in Newfoundland.', 'https://www.themealdb.com/images/media/meals/kzi6p51764787198.jpg',
         'Canadian', 'Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Figgy Duff'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('all purpose flour', '2 cups'),
  ('brown sugar', '1/2 cup'),
  ('baking powder', '2 tsp'),
  ('ginger', '1 tsp'),
  ('allspice', '1 tsp'),
  ('cinnamon', '1 tsp'),
  ('raisins', '1 cup'),
  ('melted butter', '1/3 cup'),
  ('molasses', '1/2 cup'),
  ('water', '1 tablespoon')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Flapper Pie', 'Preheat the oven to 350˚F.
Mix all the crust ingredients (graham cracker crumbs, melted butter, granulated sugar and ground cinnamon) in a medium bowl. Set aside about 2 Tbsp (30 mL) for later and press the mixture into a 9-inch deep-dish pie plate in the bottom and up the sides. Bake crust for 10 minutes, it will only brown slightly.
Combine the vanilla custard filling ingredients (milk, granulated sugar, cornstarch, egg yolks, vanilla extract and salt together) and cook on medium heat, stirring constantly, until it bubbles and thickens to the texture of pudding. Set aside to cool while you make the meringue topping.
In the bowl of a stand mixer fitted with the beater attachment or in a large bowl using an electric mixer beat the meringue ingredients (egg whites, granulated sugar, cream of tartar) together until it holds stiff and glossy peaks.
To assemble the pie, pour the filling into the crust and top with a thick layer of the meringue, making little spikes that will brown on top. Sprinkle the reserved crumb over the top and place it into the preheated oven.
Bake until the meringue browns, around 10 minutes, making sure to watch it carefully.
Chill in the fridge and eat within a few hours of baking. This pie is best eaten the same day as the meringue will soften and liquify.', 'https://www.themealdb.com/images/media/meals/6ht8141764786479.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Flapper Pie'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('graham cracker crumbs', '1 1/2 cups'),
  ('melted butter', '6 tablespoons'),
  ('sugar', '1/2 cup'),
  ('cinnamon', '1/2 tsp'),
  ('milk', '2 1/2 cups'),
  ('sugar', '1/2 cup'),
  ('cornstarch', '1/4 cup'),
  ('egg yolks', '3'),
  ('vanilla extract', '1 tsp'),
  ('salt', '1/4 tsp'),
  ('egg white', '3'),
  ('sugar', '1/4 cup'),
  ('cream of tartar', '1/4 tsp')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Hodge Podge', 'First, cook your vegetables. Bring a large pot of salted water to boil. Par-cook carrots and potatoes for five minutes until carrots and potatoes are fork tender, then blanch the peas and beans for about a minute in the same pot. Strain vegetables and set aside.
In a heavy-bottomed pot or Dutch oven, melt butter over medium heat, add vegetables, and cook to warm through.
Add milk and cream and bring the soup to a boil. Turn the heat down to low and season with salt and pepper.
Add dill and chives and let simmer for at least 10 minutes. Serve warm.', 'https://www.themealdb.com/images/media/meals/xihv0c1764447887.jpg',
         'Canadian', 'Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Hodge Podge'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('new potatoes', '1 lb'),
  ('carrots', '1 lb'),
  ('green beans', '1 cup'),
  ('peas', '1/2 cup'),
  ('dill', '1 tablespoon'),
  ('chives', '1 tablespoon'),
  ('milk', '3 Cups'),
  ('heavy cream', '1/2 cup'),
  ('butter', '1/2 cup'),
  ('salt', '1/2 tsp'),
  ('black pepper', '1/4 tsp')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Jam jam cookies', 'Preheat the oven to 350 °F (180 °C) and line a large baking sheet with parchment paper.
In a stand mixer with the paddle attachment, cream the butter, white sugar and egg until combined, then add the molasses and vanilla and mix until smooth.
Once combined, add the baking soda water mixture and mix for another minute to combine.
Combine dry ingredients; mix baking powder, cinnamon, flour and salt in a separate bowl then add to the wet ingredients a little at a time, mixing on low until fully combined and scraping down the sides to ensure everything is incorporated. The dough should be easily shaped.
Portion dough with a small spoon, roll them into balls and place them on the lined cookie sheet, press them into flat discs using a floured glass or your moistened palm.
Place cookies on parchment-lined baking sheets and bake for 10-12 mins. Remove from the oven and let them cool for at least 10 minutes.
Once cooled the cookie sandwiches by spreading at least two teaspoons of your favourite jam between the two cookies. Repeat and enjoy with a cup of tea.', 'https://www.themealdb.com/images/media/meals/sktequ1764447186.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Jam jam cookies'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('egg', '1'),
  ('butter', '1 cup'),
  ('sugar', '1 cup'),
  ('molasses', '1/2 cup'),
  ('vanilla', '1 tsp'),
  ('baking powder', '2 tsp'),
  ('water', '3  tablespoons'),
  ('baking powder', '2 tablespoons'),
  ('cinnamon', '1 tsp'),
  ('salt', '2 tsp'),
  ('flour', '4 cups'),
  ('jam', '2 cups')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Jiggs Dinner', 'The night before, break salt beef into big chunks and soak in water overnight, at least 8-10 hours. Put split peas into a bowl and cover with water to soak overnight.
Drain the salt beef and place it into a large stockpot. Cover with fresh water, at least 6-7 litres. Place the split peas into a pease pudding canvas bag or triple layer of cheesecloth and tie, making sure to leave room for peas to expand inside the bag.
Put the bag inside the pot, tying the strings to the outside handle so it doesn''t stick to the bottom of the pot with the salt beef. Bring to a boil, then lower the heat and simmer for 2 hours.
Remove the peas pudding bag and empty contents into a bowl, mixing with butter and pepper for taste. Set aside.
Add your cabbage to the pot and boil for 20 more minutes. Then add turnip, carrots and potatoes then boil for 20 more, or until vegetables are tender.
Remove salt beef and vegetables from the pot and put them on a platter.
Use the cooking liquid in two ways; as a pot liquor which some people like to drink or reduce it to make a jus or gravy to pour over the meal.', 'https://www.themealdb.com/images/media/meals/z1tfnw1764443171.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Jiggs Dinner'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('beef', '2 Lbs'),
  ('yellow split peas', '1 cup'),
  ('cabbage', '1 head'),
  ('carrots', '6'),
  ('turnips', '1 large'),
  ('potatoes', '8'),
  ('butter', '3  tablespoons'),
  ('black pepper', 'To taste')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Molasses Baked Beans', 'Place the dried beans into a Dutch oven with 6 cups (1.5 L) of water. Soak overnight.
Drain and pour beans back into the pot with enough water to cover the beans by a couple of inches, cook for 30 minutes until they are tender but still firm. Drain beans, making sure to reserve cooking liquid, set aside.
Preheat the oven to 325 °F (160 °C). While the oven is preheating, cook pork over medium-high heat in the Dutch Oven until fat is rendered and pork is beginning to brown, then add the onion cooking until tender.
Add the beans back to the pot, along with molasses, brown sugar, apple cider vinegar, ground mustard, salt and pepper and 3 cups (750 mL) of reserved bean water.
Bake uncovered for 3 to 5 hours until the beans are tender, and the sauce has thickened, and the edges of the pot get sticky.
(Note: if beans get dry, add another cup of water.)', 'https://www.themealdb.com/images/media/meals/9tddhg1764443699.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Molasses Baked Beans'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('white navy beans', '2 cups'),
  ('bacon', '1/2 lb'),
  ('onion', '1 medium'),
  ('molasses', '1/2 cup'),
  ('brown sugar', '1/4 cup'),
  ('cider vinegar', '2 tablespoons'),
  ('mustard', 'Ground'),
  ('salt', 'To taste'),
  ('pepper', 'To taste')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Montreal Smoked Meat', 'To make the cure, in a small bowl mix together salt, pink salt, black pepper, coriander, sugar, bay leaf, and cloves. Coat entire brisket with the cure and place in an extra-large resealable plastic bag. Place in the coldest part of the refrigerator and cure for 4 days, flipping brisket twice a day.
Remove brisket from bag and wash as much cure off as possible under cold running water. Place brisket in a large container and fill with water and let soak for 2 hours, replacing water every 30 minutes. Remove from water and pat dry with paper towels.
To make the rub, mix together black pepper, coriander, paprika, garlic powder, onion powder, dill weed, mustard, celery seed, and crushed red papper in a small bowl. Coat entire brisket with the rub.
Fire up smoker or grill to 225 degrees, adding chunks of smoking wood chunks when at temperature. When wood is ignited and producing smoke, place brisket in, fat side up, and smoke until an instant read thermometer registers 165 degrees when inserted into thickest part of the brisket, about 6 hours.
Transfer brisket to large roasting pan with V-rack. Place roasting pan over two burners on stovetop and fill with 1-inch of water. Bring water to a boil over high heat, reduce heat to medium, cover roasting pan with aluminum foil, and steam brisket until an instant read thermometer registers 180 degrees when inserted into thickest part of the meat, 1 to 2 hours, adding more hot water as needed.
Transfer brisket to cutting board and let cool slightly. Slice and serve, preferably on rye with mustard.', 'https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Montreal Smoked Meat'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('beef brisket', '1'),
  ('salt', '3 tbs'),
  ('black pepper', '3 tbs'),
  ('coriander', '1 tbs'),
  ('sugar', '1 tbs'),
  ('bay leaf', '1 tsp'),
  ('cloves', '1 tsp'),
  ('black pepper', '3 tbs'),
  ('coriander', '1 tbs'),
  ('paprika', '1 tbs'),
  ('garlic', '1 tbs'),
  ('onion', '1 tbs'),
  ('dill', '1 tbs'),
  ('english mustard', '1 tsp'),
  ('celery salt', '1 tbs'),
  ('red pepper flakes', '1 tsp')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Nanaimo Bars', 'Start by making the biscuit base. In a bowl, over a pan of simmering water, melt the butter with the sugar and cocoa powder, stirring occasionally until smooth. Whisk in the egg for 2 to 3 mins until the mixture has thickened. Remove from heat and mix in the biscuit crumbs, coconut and almonds if using, then press into the base of a lined 20cm square tin. Chill for 10 mins.
For the middle layer, make the custard icing; whisk together the butter, cream and custard powder until light and fluffy, then gradually add the icing sugar until fully incorporated. Spread over the bottom layer and chill in the fridge for at least 10 mins until the custard is no longer soft.
Melt the chocolate and butter together in the microwave, then spread over the chilled bars and put back in the fridge. Leave until the chocolate has fully set (about 2 hrs). Take the mixture out of the tin and slice into squares to serve.', 'https://www.themealdb.com/images/media/meals/vwuprt1511813703.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Nanaimo Bars'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('custard', '125g'),
  ('caster sugar', '50g'),
  ('cocoa', '5 tbs'),
  ('egg', '1 beaten'),
  ('digestive biscuits', '200g shredded'),
  ('desiccated coconut', '100g'),
  ('almonds', '50g'),
  ('butter', '100g'),
  ('double cream', '4 tbs'),
  ('custard powder', '3 tbs'),
  ('icing sugar', '250g'),
  ('dark chocolate', '150g'),
  ('butter', '50g')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Pate Chinois', 'In a large pot of salted water, cook the potatoes until they are very tender. Drain.
With a masher, coarsely crush the potatoes with at least 30 ml (2 tablespoons) of butter. With an electric mixer, purée with the milk. Season with salt and pepper. Set aside.
With the rack in the middle position, preheat the oven to 190 °C (375 °F).
In a large skillet, brown the onion in the remaining butter. Add the meat and cook until golden brown. Season with salt and pepper. Remove from the heat.
Lightly press the meat at the bottom of a 20-cm (8-inch) square baking dish. Cover with the corn and the mashed potatoes. Sprinkle with paprika and parsley.
Bake for about 30 minutes. Finish cooking under the broiler. Let cool for 10 minutes.', 'https://www.themealdb.com/images/media/meals/yyrrxr1511816289.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Pate Chinois'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('potatoes', '4 cups'),
  ('butter', '60ml'),
  ('milk', '½ cup'),
  ('beef', '450g'),
  ('onion', '1 finely chopped'),
  ('creamed corn', '500ml'),
  ('paprika', 'to taste'),
  ('parsley', 'to taste'),
  ('salt', 'Dash'),
  ('pepper', 'Dash')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Pouding chomeur', 'In a large bowl, with an electric mixer, mix the butter and sugar till the mix is light.
Add eggs and vanilla and mix.
In another bowl, mix flour and baking powder.
Alternate flour mix and milk to the butter mix.
Pour into a 13 inch by 9 inch greased pan.
MAPLE SAUCE.
In a large casserole, bring to boil the syrup, brown sugar, cream and butter and constantly stir.
Reduce heat and and gently cook 2 minutes or till sauce has reduced a little bit.
Pour sauce gently over cake.
Bake at 325°f (160°c) about 35 minutes or till cake is light brown and when toothpick inserted comes out clean.', 'https://www.themealdb.com/images/media/meals/yqqqwu1511816912.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Pouding chomeur'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('butter', '½ cup'),
  ('sugar', '1 cup'),
  ('eggs', '2'),
  ('vanilla extract', '1 tsp'),
  ('flour', '2 cups'),
  ('baking powder', '1 tsp'),
  ('milk', '1 1/4 cup'),
  ('maple syrup', '1 1/2 cup'),
  ('brown sugar', '1 1/2 cup'),
  ('single cream', '1 1/2 cup'),
  ('butter', '1/3 cup')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Poutine', 'Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).
Warm gravy in saucepan or microwave.
Place the fries into the hot oil, and cook until light brown, about 5 minutes.
Remove to a paper towel lined plate to drain.
Place the fries on a serving platter, and sprinkle the cheese over them.
Ladle gravy over the fries and cheese, and serve immediately.', 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Poutine'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('vegetable oil', 'Dash'),
  ('beef gravy', '1 Can'),
  ('potatoes', '5 thin cut'),
  ('cheese curds', '2 cups')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Rappie Pie', 'Preheat oven to 400 degrees F (200 degrees C). Grease a 10x14x2-inch baking pan.
Heat margarine in a skillet over medium heat; stir in onion. Cook and stir until onion has softened and turned translucent, about 5 minutes. Reduce heat to low and continue to cook and stir until onion is very tender and dark brown, about 40 minutes more.
Bring chicken broth to a boil in a large pot; stir in chicken breasts, reduce heat, and simmer until chicken is no longer pink at the center, about 20 minutes. Remove from heat. Remove chicken breasts to a plate using a slotted spoon; reserve broth.
Juice potatoes with an electric juicer; place dry potato flesh into a bowl and discard juice. Stir salt and pepper into potatoes; stir in enough reserved broth to make the mixture the consistency of oatmeal. Set remaining broth aside.
Spread half of potato mixture evenly into the prepared pan. Lay cooked chicken breast evenly over potatoes; scatter caramelized onion evenly over chicken. Spread remaining potato mixture over onions and chicken to cover.
Bake in the preheated oven until golden brown, about 1 hour. Reheat chicken broth; pour over individual servings as desired.', 'https://www.themealdb.com/images/media/meals/ruwpww1511817242.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Rappie Pie'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('butter', '2 tbs'),
  ('onions', '2 chopped'),
  ('chicken stock', '4 qt'),
  ('chicken breast', '1.5kg'),
  ('potatoes', '4kg'),
  ('salt', '2 tbs'),
  ('black pepper', '1tbsp')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Saskatoon Pie', 'To make the pastry, place the flour and salt in a large bowl. Mix well. Add the cubes of butter and shortening and mix them in (I like to use my hands to mix the fat into the flour, but you can use a pastry blender) just until it looks like coarse oatmeal with some pea-sized bits remaining. Place the egg in a 2-cup measure and beat it with a fork. Beat in the vinegar and just enough ice-cold water to bring it to the 1-cup mark. Stir this into the flour mixture, just until the dough clings together. I like to use my hands for this part as well, but a wooden spoon would also work. Try not to overmix it.
On a lightly floured surface, gather the dough into a ball and divide it into 5 evenly sized portions. Shape each portion into a disc and wrap tightly in plastic. Chill 2 of these discs for 1 hour. Freeze the other 3 in a resealable freezer bag for future use. The pastry keeps well in the freezer for up to 2 months.
Preheat the oven to 350°F. Place the rack in the lower third of the oven. Line a baking sheet with aluminum foil to catch drippings.
On a lightly floured surface, roll out 1 disc of pastry into a 12-inch circle, or thereabouts. Place it in the bottom of a 9-inch pie plate, with the pastry overhanging the edges of the pie plate.
To make the filling, place the saskatoon berries in a large bowl and stir in the 1/2 cup sugar and the cornstarch until well combined. Pour the berry mixture into the bottom of the pie. Dot with the butter. On a lightly floured surface, roll out the pastry in another 12-inch circle for the top crust. Use a ruler to guide you when cutting the pastry into 6 wide, long strips to keep the edges straight. Save the 2 end pieces in case you need to do any patching. I like wide strips, but if you like a thinner look, feel free to cut thin strips of pastry. Weave the pastry strips, going over and under, making sure they connect with the edges of the pie crust. Fold over the edges of the bottom crust, tucking in the lattice ends. This will help to trap the juices and give a rustic look.
If you prefer a cleaner, tidier look, you can trim the overhanging pieces and crimp the edges with a fork. Brush the top of the pie with the egg wash. Sprinkle with the remaining Tbsp sugar. Place the pie on the prepared baking sheet and bake it for about 90 – 100 minutes, until it’s golden brown and bubbling. Remove the pie from the oven and place it on a wire rack to cool.
Serve the pie warm or at room temperature with whipped cream or ice cream. Makes 6 servings. This keeps well if covered with plastic and refrigerated for up to 4 days.', 'https://www.themealdb.com/images/media/meals/5xdrkw1764444472.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Saskatoon Pie'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('all purpose flour', '6 cups'),
  ('salt', '2 tsp'),
  ('unsalted butter', '1 cup'),
  ('vegetable shortening', '1 cup'),
  ('egg', '1 large'),
  ('vinegar', '1 tablespoon'),
  ('water', 'Splash'),
  ('saskatoon berries', '5 Cups'),
  ('sugar', '1/2 cup'),
  ('sugar', '1 tablespoon'),
  ('cornstarch', '3  tablespoons'),
  ('unsalted butter', '2 tablespoons'),
  ('egg', '1 beaten'),
  ('water', '1 tablespoon')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Split Pea Soup', 'Put the gammon in a very large pan with 2 litres water and bring to the boil. Remove from the heat and drain off the water – this helps to get rid of some of the saltiness. Recover with 2 litres cold water and bring to the boil again. Put everything but the frozen peas into the pan and bring to the boil. Reduce to a simmer and cook for 1½-2½ hrs, topping up the water as and when you need to, to a similar level it started at. As the ham cooks and softens, you can halve it if you want, so it is all submerged under the liquid. When the ham is tender enough to pull into shreds, it is ready.
Lift out the ham, peel off and discard the skin. While it is still hot (wear a clean pair of rubber gloves), shred the meat. Remove bay from the soup and stir in the frozen peas. Simmer for 1 min, then blend until smooth. Add a splash of water if too thick, and return to the pan to heat through if it has cooled, or if you are making ahead.
When you are ready to serve, mix the hot soup with most of the ham – gently reheat if made ahead. Serve in bowls with the remaining ham scattered on top, and eat with crusty bread and butter.', 'https://www.themealdb.com/images/media/meals/xxtsvx1511814083.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Split Pea Soup'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('ham', '1kg'),
  ('peas', '200g (soaked overnight)'),
  ('onions', '2 chopped'),
  ('carrots', '2 chopped'),
  ('bay leaves', '2'),
  ('celery', '1 chopped'),
  ('frozen peas', '300g'),
  ('bread', 'to serve')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Sugar Pie', 'Preheat oven to 350 degrees F (175 degrees C). Grease a 9-inch pie dish.
Place the brown sugar and butter in a mixing bowl, and beat them together with an electric mixer until creamy and very well combined, without lumps. Beat in eggs, one at a time, incorporating the first egg before adding the next one. Add the vanilla extract and salt; beat the flour in, a little at a time, and then the milk, making a creamy batter. Pour the batter into the prepared pie dish.
Bake in the preheated oven for 35 minutes; remove pie, and cover the rim with aluminum foil to prevent burning. Return to oven, and bake until the middle sets and the top forms a crusty layer, about 15 more minutes. Let the pie cool to room temperature, then refrigerate for at least 1 hour before serving.', 'https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Sugar Pie'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('brown sugar', '2 cups'),
  ('butter', '¼ cup'),
  ('eggs', '2'),
  ('vanilla extract', '1 tsp'),
  ('salt', '1 tsp'),
  ('plain flour', '½ cup'),
  ('milk', '1 1/2 cups')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Timbits', 'Sift together dry ingredients.
Mix together wet ingredients and incorporate into dry. Stir until smooth.
Drop by teaspoonfuls(no bigger) into hot oil (365 degrees, no hotter), turning after a few moments until golden brown on all sides.
Remove and drain.
Roll in cinnamon sugar while still warm and serve.', 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
         'Canadian', 'Eggetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Timbits'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('flour', '2 cups'),
  ('sugar', '1/3 cup'),
  ('baking powder', '3 tsp'),
  ('salt', '½ tsp'),
  ('egg', '1 beaten'),
  ('milk', '¾ cup'),
  ('oil', '3 tbs'),
  ('oil', 'for frying'),
  ('icing sugar', 'garnish')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

with ins as (
  insert into public.recipes (title, instructions, image_url, cuisine, diet, status, author_id)
  select 'Tourtiere', 'Heat oven to 200C/180C fan/gas 6. Boil the potato until tender, drain and mash, then leave to cool. Heat the oil in a non-stick pan, add the mince and onion and quickly fry until browned. Add the garlic, spices, stock, plenty of pepper and a little salt and mix well. Remove from the heat, stir into the potato and leave to cool.
Roll out half the pastry and line the base of a 20-23cm pie plate or flan tin. Fill with the pork mixture and brush the edges of the pastry with water. Roll out the remaining dough and cover the pie. Press the edges of the pastry to seal, trimming off the excess. Prick the top of the pastry case to allow steam to escape and glaze the top with the beaten egg.
Bake for 30 mins until the pastry is crisp and golden. Serve cut into wedges with a crisp green salad. Leftovers are good cold for lunch the next day, served with a selection of pickles.', 'https://www.themealdb.com/images/media/meals/ytpstt1511814614.jpg',
         'Canadian', 'Non Vegetarian', 'approved',
         (select id from public.profiles where role = 'admin' order by created_at limit 1)
  where not exists (select 1 from public.recipes where lower(title) = lower('Tourtiere'))
  returning id
)
insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity)
select ins.id, i.id, 'core', v.measure
from ins
join (values
  ('potatoes', '1 medium'),
  ('sunflower oil', '1 tsp'),
  ('pork', '500g'),
  ('onion', '1 finely chopped'),
  ('garlic clove', '1 finely chopped'),
  ('cinnamon', '¼ tsp'),
  ('allspice', '¼ tsp'),
  ('nutmeg', '¼ tsp'),
  ('vegetable stock', '100ml'),
  ('shortcrust pastry', '400g'),
  ('egg', 'To Glaze')
) as v(name, measure) on true
join public.ingredients i on lower(i.name) = v.name
on conflict (recipe_id, ingredient_id) do nothing;

commit;